config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :textbooks
    resources :users
    

    root to: "textbooks#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#show"
  resources :textbooks do
    resources :comments
  end
  get "about" => "about#about"
  get "sell" => "sell#sell"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :textbook
  
  validates :commenters, presence:true
  validates :body, presence:true
end

app/models/textbook.rb
class Textbook < ApplicationRecord
    has_many:comments, dependent: :destroy
    belongs_to:user

    
    validates :user, presence:true
    validates :name, presence:true, uniqueness: { scope: :user_id }
    validates :description, presence:true
    validates :price, presence:true
    validates :course, presence:true
    validates :instructor, presence:true
end 

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  include Clearance::User
  has_many :textbooks
 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: "admin@admin.com", password: "admin"
    before_action :authenticate_admin

    
    def authenticate_admin
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/textbooks_controller.rb
module Admin
  class TextbooksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Textbook.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Textbook.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
 
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_filter :require_login
    

    
    def new
        @comment = textbooks.comments.build
    end


    def create
        @textbook = Textbook.find(params[:textbook_id])
        @comment = @textbook.comments.create(comment_params)
        redirect_to textbook_path(@textbook),notice:"Comment Added"
    end
  
    def destroy
        @textbook = Textbook.find(params[:textbook_id])
        @comment = @textbook.comments.find(params[:id])
        @comment.destroy
        redirect_to textbook_path(@textbook),notice: "Deleted comment"
    end

    private
    
    def comment_params
        params.require(:comment).permit(:commenters, :body)
    end
    
end

app/controllers/sell_controller.rb
class SellController < ApplicationController
    before_action:require_login
    
    def sell
        @textbooks = Textbook.all.order('created_at DESC')
    end
end
  

app/controllers/textbooks_controller.rb
class TextbooksController < ApplicationController
    before_action:require_login
    
    def index
        @textbooks = current_user.textbooks.order(:id)
    end
    
    def show
        @textbook = Textbook.find(params[:id])
        @textbooks = Textbook.all.order("created_at DESC")
    end
    
    def new
        @textbook = current_user.textbooks.build
    end
    
    def create
        @textbook = current_user.textbooks.build(textbook_params)
        
        if @textbook.save
            redirect_to textbook_path(@textbook), notice: "Textbook Added!"
        else
         @errors = @textbook.errors.full_messages
            render :new
        end
    end
    
    def edit
        @textbook = current_user.textbooks.find(params[:id])
    end
    
    def update
        @textbook = current_user.textbooks.find(params[:id])
        
        if @textbook.update_attributes(textbook_params)
            redirect_to textbook_path(@textbook), notice: "Textbook Added!"
        else
         @errors = @textbook.errors.full_messages
            render :new
        end    
    end
    
    def destroy
        textbook = current_user.textbooks.find(params[:id])
        textbook.destroy
        redirect_to textbooks_path, notice: "Deleted Textbook: #{textbook.name}"
    end
    
    private
    
    def textbook_params
        params.require(:textbook).permit(:name, :course, :instructor, :price, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_class(flash_type)
    case flash_type.to_sym
    when :notice
        "alert-success"
    when :alert
        "alert-warning"
    when :error
        "alert-danger"
    end
    
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/about/about.html.erb
 <head>
 <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
 </head>
 
 <h3 style= "font-family: 'Lato', sans-serif;">What is SFU Book Club?</h3>
  <p style="font-family: Georgia;font-size:15px;">SFU Book Club is a platform to buy and sell used textbooks. Textbooks are bought and sold directly from other students. SFU Book Club does not charge anything for using this site. </p>

<h3 style= "font-family: 'Lato', sans-serif;">Why do you choose us to buy textbooks?</h3>
 <p style="font-family: Georgia;font-size:15px;">Our price is cheaper than the bookstore, and you can find many suggestions of the book that you want. We offer more choices in our SFU Book Club</p>

<h3 style= "font-family: 'Lato', sans-serif;">Why do you use us to sell your textbooks?</h3>
<p style="font-family: Georgia;font-size:15px;">You can sell your old textbooks conveniently and fast. You can communicate with the customers to learn more about their ideas and what they are looking for. </p>

  <h3 style= "font-family: 'Lato', sans-serif;">How to buy a textbook?</h3>
  <p style="font-family: Georgia;font-size:15px;">Textbooks are posted by other students from SFU. You can search for the desired textbook based on textbook name, author, or course number. From there you may contact and a message to the seller directly through email.</p>

  <h3 style= "font-family: 'Lato', sans-serif;">How to post a textbook for sale?</h3>
  <p style="font-family: Georgia;font-size:15px;">From your own account, you may post textbooks for sale. Simply fill in the form stating the textbook name, author, course number, quality of textbook and price. You may also leave additional comments about the textbook if needed.</p>

  <h3 style= "font-family: 'Lato', sans-serif;">How to recieve the textbook?</h3>
  <p style="font-family: Georgia;font-size:15px;">Type of payment transaction, when and where to recieve the textbook is completely upto the seller and buyer to decide.</p>
  
  
<footer >
<hr>

<div  class="text" style="font-family: 'Lato', sans-serif;text-align:right;color:#A52A2A;font-size:20px;" >Phone: 778-866-8888 </div>
<br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:right;color:#A52A2A;font-size:20px;" >Email: sellbook@gmail.com  </div>
<br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:right;color:#A52A2A;font-size:20px;" >Address: 9888 Cameron Street </div>
<br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:right;color:#A52A2A;font-size:20px;" >Advisor: Mr. Li </div>


</footer>

<p1>
 <div  class="text" style="font-family: 'Lato', sans-serif;text-align:left;color:#A52A2A;font-size:20px;" >About Us </div>
 <br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:left;color:#A52A2A;font-size:15px;" >We are an enthusiastic group of website developers that are always looking for new ways to improve our site. </div>
 <br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:left;color:#A52A2A;font-size:15px;" >Leave us a message if you have any questions, concerns or suggestions for our website!  </div>
 <br> <div class="text" style="font-family: 'Lato', sans-serif;text-align:left;color:#A52A2A;font-size:15px;" >Team Members: Tommy &nbsp; Shelly &nbsp; Archer &nbsp; Emilie &nbsp; Francis</div> 
<br>
 
 
 </p1>

app/views/admin/application/_collection.html.erb
<table aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(sanitized_order_params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "helpers.label.#{resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit), valid_action?(:destroy)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) if valid_action? :show -%>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show"
               >
              <%= render_field attribute %>
            </a>
          </td>
        <% end %>

        <% if valid_action? :edit %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) %></td>
        <% end %>

        <% if valid_action? :destroy %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/_form.html.erb
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/edit.html.erb
<% content_for(:title) { "#{t("administrate.actions.edit")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "#{t("administrate.actions.show")} #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) if valid_action? :show %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/index.html.erb
 
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <% if show_search_bar %>
    <%= render "search", search_term: search_term %>
  <% end %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 style= "font-family: 'Lato', sans-serif" class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>
  <div style= "font-family: 'Lato', sans-serif;">
    <%= link_to "Home","../../", class: "button" %>
    <%= link_to(
      "#{t("administrate.actions.new")} #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action? :new %>
  </div>
  
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/application/new.html.erb
<% content_for(:title) { "#{t("administrate.actions.new")} #{page.resource_name.titleize}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/show.html.erb
<% content_for(:title) { "#{t("administrate.actions.show")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      "#{t("administrate.actions.edit")} #{page.page_title}",
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action? :edit %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute %></dd>
    <% end %>
  </dl>
</section>

app/views/comments/_comment.html.erb
<p class = comment_commente>
    <strong style="font-family: 'Lato', sans-serif;font-size:15px">Commenter:</strong>
        <span style="font-family: Georgia;color:#97454a; font-size:15px">
        <%= comment.commenters %>
        </span>
</p>

<p class = comment_body>
    <strong style="font-family: 'Lato', sans-serif;font-size:15px">Comment:</strong>
        <span style="font-family: Georgia;color:#97454a; font-size:15px">
        <%= comment.body %>
        </span>
</p>

<p class = comment_time>
    <%= time_ago_in_words(comment.created_at) %> ago
</p>

<p> 
    <%= link_to 'Delete Comment', [comment.textbook, comment], 
                method: :delete, 
                class: "button",
                data: { confirm: 'Are you sure?' } %> 
</p>
   

app/views/comments/_form.html.erb
<%= form_for ([@textbook,@textbook.comments.build]) do |f| %>


    <p>
        <%= f.label :commenters %><br>
        <%= f.text_field :commenters, :maxlength=>"20",autofocus: true, placeholder: "name", :required => 'required' %>
    </p>
  
    <p>
        <%= f.label :body %><br> 
        <%= f.text_area :body, :size =>"35x7",autofocus: true, placeholder: "message", :required => 'required' %>
    </p>    
    <br>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<style>

#container_body {
  text-align: left;
}
  
#bar_font {
  font-size: 17px;
}
  
</style>


<html lang="en">
  <head>
    <title>SFU BookClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    
<header class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-left">
        <li id="bar_font"><%= link_to "SFU BookClub", root_path %></li>
        <li id="bar_font"><%= link_to "Admin", admin_root_path %></li>
        </ul>
    <ul class="nav navbar-nav navbar-right">    
    <% if signed_in? %>
      <li id="bar_font"><%= link_to "About", about_path %></li>
      <li id="bar_font"><%= link_to "For Sale", sell_path %></li>
      <li id="bar_font"><%= link_to "My Textbooks", textbooks_path %></li>
      <li id="bar_font"><%=  link_to "Sign out", sign_out_path, method: :delete %></li>
    <% else %>
      <li id="bar_font"><%= link_to 'Sign in', sign_in_path %></li>
    <% end %>
    </ul>
    </div>
    </nav>
</header>

<section class="container", id="container_body">
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
      <% end %>
    </div>
    
    <%= yield %>
</section>
  </body>
</html>

app/views/sell/sell.html.erb
<style>

#div_textbook {
    background-color: lightgrey;
    border: 3px dashed #ddd;
}

#book_name {
    color: #7d171d;
}

#book_detail {
    font-family: Georgia;
    font-size: 16px;
}
    
    
#div_search_button {
    display: inline;
    margin-left: 20px;
}

#div_search_text {
    display: inline;
}

</style>


<div class="title-container">
    <h1 style= "font-family: 'Lato', sans-serif;">Textbooks for Sale</h1>
</div>




<div class="textbooks">
    <% @textbooks.each do|textbook| %>
    <div class="textbook">
        <div class="thumbnail" id="div_textbook">
            <div class="caption">
                <h3 style= "font-family: 'Lato', sans-serif;" ><%= 'Book name: '%><%= link_to textbook.name, textbook_path(textbook), id:"book_name"%>&nbsp &nbsp &nbsp &nbsp<%= "Price:"%><%= "  $"%><%= textbook.price%></h3>
                <p id="book_detail"><%= "Course: " %><%= textbook.course%>&nbsp &nbsp &nbsp &nbsp<%= "Instructor: " %><%= textbook.instructor %></p>
                <p id="book_detail"><%= "Description: " %><%= textbook.description %></p>
                <p id="book_detail" class="data"><%= "Posted: " %> <%= textbook.created_at.strftime("%B %d, %Y") %> </p>
            </div>
            
        </div>
    </div>
<% end %>
</div>


<div>
    <p id="div_search_text" style="font-family: Georgia;font-size:18px"><%= "Can't find the right book?"%></p> 
    <INPUT TYPE="button" onClick="history.go(0)" VALUE="Search Here" id="div_search_button"> 
</div>

<script>
  (function run() {
    var cx = '004265675826218390244:f5zzskvjay8';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    //gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    gcse.src = "/../assets/javascripts/api.js";
    //gcse.url
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
  run();
</script>
<gcse:search></gcse:search>

app/views/textbooks/_form.html.erb
<%= form_for @textbook do |form| %>
    
    <% if @textbook.errors.any? %>
    <div class="alert alert-danger errors">
        <h3> <%= pluralize(@textbook.errors.count,"error") %> prevented this textbook from saving </h3>
            <ul>
                <% @textbook.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
    </div>
<% end %>
    
    <div class = "form-group">
        <%= form.label:name %>
        <%= form.text_field :name, class:"form-control" %>
    </div>

    <div class = "form-group">
        <%= form.label:course %>
        <%= form.text_field :course, class:"form-control" %>
    </div>
    
    <div class = "form-group">
        <%= form.label:instructor %>
        <%= form.text_field :instructor, class:"form-control" %>
    </div>
    
    <div class = "form-group">
        <%= form.label:price %>
        <%= form.text_field :price, class:"form-control" %>
    </div>
    
    <div class = "form-group">
        <%= form.label:description %>
        <%= form.text_area :description, class: "form-control" %>
    </div>
    
    <div class = "actions">
        <%= form.submit class: "btn btn-primary" %>
    </div>
    
<% end %>

    

app/views/textbooks/edit.html.erb
<div class="title-container">
    <h1> Edit Textbook</h1>
</div>
<%= render partial: "form" %>

app/views/textbooks/index.html.erb
<head>
<style>
#price_tag {
    color: darkred;
    font-size: 16px;
    font-weight: bold;
    font-family: 'Lato', sans-serif;
}

#div_textbook {
    display: block;
    padding: 4px;
    margin-bottom: 20px;
    line-height: 1.42857143;
    background-color: #fff;
    

    -webkit-transition: border 0.2s ease-in-out;
    -o-transition: border 0.2s ease-in-out;
    transition: border 0.2s ease-in-out;
    max-width: 566px;
    min-width: 566px;
    max-height: 180px;
    min-height: 180px;
    
    background-color: lightgrey;
    
	border: 3px dashed #ddd;
	box-shadow: 0 0 0 3px #fff, 0 0 0 5px #ddd, 0 0 0 10px #fff, 0 0 2px 10px #eee;
	margin-bottom: 1px;
}

#div_item {
    display: inline;
    overflow: hidden;   
    margin: 1px;
    font-family: 'Lato', sans-serif;
    display: inline-block;
}

#div_detail {
    display: inline;
    margin-right: 50px;
    color: black;
    font-family: 'Lato', sans-serif;
    font-size: 16px;
}

#book_name {
    color: black;
    font-family: 'Lato', sans-serif;
    font-size: 24px;
    font-weight: bold;
}


</style>
</head>

<div class="title-container">
    <h1 style= "font-family: 'Lato', sans-serif;">Textbooks</h1>
    <%= link_to "New Textbook", new_textbook_path, class: "btn btn-default"%>
</div>
    
<div class="textbooks">
    <% @textbooks.each do|textbook| %>
    <div id="div_item">
        <div id="div_textbook">
            <div class="caption">
                <h3 id="book_name"> <%= link_to textbook.name, textbook_path(textbook), id: "book_name" %></h3>
                <p id="div_detail">Course: <%= textbook.course %></p>
                <p id="div_detail">Instructor: <%= textbook.instructor %></p>
                <p id="price_tag">CDN$ <%= textbook.price %></p>
                <!--
                <p>Description: <%= truncate(textbook.description, length: 150) %></p>
                -->
                <p id="div_detail"> <%= time_ago_in_words(textbook.created_at) %> ago</p>
                <p>
                    <%= link_to "Edit", edit_textbook_path(textbook), class: "btn btn-default" %>
                    <%= link_to "Delete", textbook_path(textbook), class: "btn btn-default",data: {
                    confirm: "Are you sure you want to delete: #{textbook.name}?",
                    }, method: :delete %>
                </p>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/textbooks/new.html.erb
<div class="title-container">
    <h1 style= "font-family: 'Lato', sans-serif;">Add Textbook</h1>
</div>
<%= render partial: "form" %>

app/views/textbooks/show.html.erb
<head>
    <style>
        .comments{
            width:50%;
            float:left;
            word-wrap:break-word; 
        }
        
      
         
        .add_comment{
            width:30%;
            float:right;
        }
    </style>
</head>

<div class ="textbooks">   
    <div id = div_textbook>
        <h3 style= "font-family: 'Lato', sans-serif;">Textbooks:</h3>
        <p style= "font-family: Georgia;color:#97454a; font-size:20px"><%= @textbook.name %></p>
        
        <h3 style= "font-family: 'Lato', sans-serif;">Course:</h3>
        <p style= "font-family: Georgia;color:#97454a; font-size:20px"><%=  @textbook.course %></p>
        
        <h3 style= "font-family: 'Lato', sans-serif;">Instructor:</h3>
        <p style= "font-family: Georgia;color:#97454a; font-size:20px"><%=  @textbook.instructor %></p>
        
        <h3 style= "font-family: 'Lato', sans-serif;">Price:</h3>
        <p style= "font-family: Georgia;color:#97454a; font-size:20px"><%=  @textbook.price %></p>
        
        <h3 style= "font-family: 'Lato', sans-serif;">Description:</h3>
        <p style= "font-family: Georgia;color:#97454a; font-size:20px"><%=  @textbook.description %></p>
        
        <div>
            <HR styple="FILTER: progid:DXImageTransform.Mocrosoft.Shadow(color:#97454a, diction:145,strength:45)" width="100%" color="#97454a" SIZE=1>
        </div>
        
        <div class="comments">
                <h3 style= "font-family: 'Lato', sans-serif;">There are <span style= "color:#97454a; font-family: 'Lato', sans-serif;"><%= @textbook.comments.count %> </span>Comments</h3>
                    <%= render @textbook.comments %></br>
        </div>
        
        <div class="space"></div>
        
        <div class="add_comment">
            <h3 style= "font-family: 'Lato', sans-serif;"> Add comments: </h3>
                <%= render 'comments/form' %>
        </div>
        
    </div>
</div>

app/views/welcome/show.html.erb
<style>
.fadeImage {
    -webkit-animation: fadein 4s; /* Safari, Chrome and Opera > 12.1 */
       -moz-animation: fadein 4s; /* Firefox < 16 */
        -ms-animation: fadein 4s; /* Internet Explorer */
         -o-animation: fadein 4s; /* Opera < 12.1 */
            animation: fadein 4s;
    display: block;
    margin: 25px auto;
}

@keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}

/* Firefox < 16 */
@-moz-keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}

/* Safari, Chrome and Opera > 12.1 */
@-webkit-keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}

/* Internet Explorer */
@-ms-keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}

/* Opera < 12.1 */
@-o-keyframes fadein {
    from { opacity: 0; }
    to   { opacity: 1; }
}

#body_background {
  background-image: url("/../assets/background/book3.jpg");
  background-size: cover;
}

#header_font {
  margin-top: 100px;
  text-align: center;
  color: white;
  font-family: 'Lato', sans-serif;
}
</style>


<html>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'welcome.scss' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
<body id="body_background" class="fadeImage">
<h1 id="header_font">Welcome to SFU Book Club!</h1>
</body>

</html>


<script>
function run(interval, frames) {
    var int = 2;
    
    function func() {
		var edit = document.getElementById("bgi");		
		edit.src="/../assets/background/book"+int+".jpg";        
		edit.classList.remove("fadeImage");		
		void edit.offsetWidth;
		edit.classList.add("fadeImage");
        int++;
        if(int === frames) { int = 1; }
    }
    
    var swap = window.setInterval(func, interval);
}
run(5000,5);
</script>




</body>
</html>